version: '3.8'
#
services:
  # Nats service
  nats-docker:
    image: nats:latest
    ports:
      - "4222:4222"

  # Redis service
  redis-docker:
    image: "redis:latest"
    ports:
      - "6379:6379"

  # PostgreSQL service
  postgres-docker:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: test_b_w
    ports:
      - "5432:5432"

#  fastapi-docker:
#    container_name: fastapi-docker
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "5051:5051"
#    depends_on:
#      - nats-docker
#      - redis-docker
#      - postgres-docker
