"""Create pairs table

Revision ID: dda02c40c3af
Revises: 
Create Date: 2024-02-01 01:10:01.036541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda02c40c3af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pairs',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(precision=5), nullable=True),
    sa.PrimaryKeyConstraint('symbol'),
    sa.UniqueConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pairs')
    # ### end Alembic commands ###
